### ISSUE TITLE
tutorials.ubuntu.com is inappropriate as a separate site

### ISSUE THREAD

**Issue by matthewpaulthomas** [ubuntudesign/tutorials.ubuntu.com#72]
Ubuntu contributors have a long and unfortunate history of launching new official Web sites that overlap in purpose with existing sites. Examples include:
- [help.ubuntu.com](https://help.ubuntu.com/), [docs.ubuntu.com](https://docs.ubuntu.com/), and [manpages.ubuntu.com](http://manpages.ubuntu.com/) being three separate official sites, when users will seldom know which (if any) will have the information they need.
- [answers.launchpad.net/ubuntu](https://answers.launchpad.net/ubuntu), [askubuntu.com](http://askubuntu.com/), [ubuntuforums.org](https://ubuntuforums.org/), and [discourse.ubuntu.com](http://discourse.ubuntu.com/) being four separate official sites, when (despite [fine distinctions](http://discourse.ubuntu.com/t/welcome-to-discourse-ubuntu-com-heres-what-this-site-is-about/1215/7)) a user is unlikely to know which site best suits their question.
- [community.ubuntu.com](http://community.ubuntu.com/), qa.ubuntu.com (retired), videos.ubuntu.com (retired), and [wiki.ubuntu.com](https://wiki.ubuntu.com/) being targeted at highly overlapping groups of Ubuntu contributors.
- In the past, [uds.ubuntu.com](http://uds.ubuntu.com/) and [summit.ubuntu.com](http://summit.ubuntu.com/) being used in parallel to organize Ubuntu Developer Summits.

This seems to happen firstly because proposing, developing (especially if a specialized CMS is involved), and claiming credit for, a separate site is much easier than doing the same for a new feature of an existing site. And secondly because the Web team and IS team do not have an effective checklist to prevent it happening. It’s harmful for many reasons: it reduces the number of people who [know that a particular site exists at all](http://discourse.ubuntu.com/t/closing-down-this-site-feedback-wanted/2700/3), dilutes search engine ranking, otherwise makes it harder to find and choose the correct site, results in inconsistent navigation through user journeys, and increases maintenance costs.

tutorials.ubuntu.com is unfortunately another example. We already have a site targeted at people developing things on Ubuntu: [developer.ubuntu.com](https://developer.ubuntu.com/en/). tutorials.ubuntu.com includes custom code for navigating tutorials, and adjusting them based on reading/following and skill level. But this does not, in any way, alter the problem that it’s completely unreasonable to expect someone to know in advance whether the topic they’re interested in has been documented as a tutorial, an article, a video, or not at all. And the addition of [a “Tutorials” page to developer.ubuntu.com](https://developer.ubuntu.com/core/tutorials) barely helps. As well as wasting reader time, the separation wastes contributor time: for example, [the developer.ubuntu.com page on setting up an Intel Joule](https://developer.ubuntu.com/core/get-started/intel-joule) and [the tutorials.ubuntu.com tutorial on exactly the same topic](https://tutorials.ubuntu.com/tutorial/setup-ubuntu-core-intel-joule) seem to have been written completely independently, with not even a link between them.

This issue will be fixed when each tutorial is embedded into the relevant section of developer.ubuntu.com, and tutorials.ubuntu.com either is retired or consists only of redirects.

Fixing this issue would incidentally fix issue #67.

**Comment by nottrobin** [comment]
Thanks @matthewpaulthomas for your input.

It seems to me that your points can be summarised as follows:

- There are many (an increasing number of?) sites with overlapping functions
- Canonicalers (people in general?) have a tendency to erroneously build new services rather than improve existing ones
- Having many separate websites & services makes it harder for people to find things they're looking for

As one of the architects of tutorials.ubuntu.com, I will try to lay out my understanding of the reasons behind its existence, especially with a view to these criticisms.

## Avoidance

We are gradually rebuilding developer.ubuntu.com anyway (developer.ubuntu.com/core is the first part of this rebuild). Therefore, I can assure you that we are not simply duplicating functionality from developer.ubuntu.com simply to avoid improving the original site itself, as we are improving the original site itself, and therefore had equal opportunity to add tutorials to developer.ubuntu.com as to create a new service.

## Finding content & multiple services

Helping users to find content is about logical structure, good menus, good links and search optimisation. This can be done well or badly, but it doesn't ultimately make much difference to this effort whether the content is structured in subpaths of the same domain or on different domains, as long as content is grouped logically.

Similarly, I don't believe there is inherently a problem with having multiple domains or services - they are simply another tool we have at our disposal for organising content and functionality. I do completely agree with you that duplicating functionality or content across multiple services leads to chaos. I hope that's not what we are doing, and that we are instead using separate domains to logically group functionality, as I will explain further below.

## The relationship between developer.ubuntu.com, tutorials.ubuntu.com and docs.ubuntu.com

The existing developer.ubuntu.com had a pretty-much universally recognised problem that it was very difficult to find what one was looking for. This can hopefully therefore be an illustration that having a single service does not inherently make things easier to find. This is exactly why we chose to rebuilt it.

In the months we spent analysing the site and deciding how to simplify the structure, we basically decided that developer.ubuntu.com was suffering from trying to be two separate things:

- An editorial site, introducing and explaining our various technical products
- A technical resource, containing some documentation (alongside all the other bits of Canonical documentation dotted around everywhere)

The technical resources could further be split into two separate types:

- Technical documentation, pertaining to specific versions of specific software products
- Step-by-step tutorials - simple, easy-to-follow guides

The problem of trying to be too many things didn't just apply to the content - it also applied to the functionality. Too many functions were being performed by a single CMS application, and it was making it a very complex and difficult piece of software to work with.

Therefore, we made the decision to split up these types of content into three separate services:

- developer.ubuntu.com for editorial descriptions of our technical offerings
- docs.ubuntu.com for all technical documentation
- tutorials.ubuntu.com for step-by-step guides

This was specifically to avoid mixing different types of content and different types of functionality. This will hopefully keep things simple, both from a content and functionality perspective, as well as freeing us up to use the most appropriate technology in each case.

## Conclusion

The decision to create tutorials.ubuntu.com was not made in a vacuum. We carefully considered the existing sites and services, and specifically decided on this structure, in full knowledge of developer.ubuntu.com and our other suite of sites.

I hope my explanation above may have allayed some of your concerns. But in any case, this decision took a long time to arrive and it is not one we will be revisiting any time soon. I will, therefore, be closing this issue.

Thanks again for your input.

**Comment by matthewpaulthomas** [comment]
I realize it must be incredibly frustrating to have worked on a site for weeks or months, only to receive a complaint that it shouldn’t exist! And it’s true there isn’t _inherently_ a problem with having multiple domains or services. In theory, it’s possible to have coherent and consistent user journeys across separate sites. login.ubuntu.com is a (fortunately minimal) case where, for technical reasons, we have no choice.

In practice, however, I’m not aware of any non-minimal case on ubuntu.com over the past decade where this has ever been achieved. It didn’t happen with any of the cases I cited, you haven’t mentioned any cases where it has happened, and it certainly hasn’t happened with tutorials.ubuntu.com. Practical examples:
- [The Intel RealSense tutorial](https://tutorials.ubuntu.com/tutorial/using-intel-realsense-sdk) can’t be found by [searching ubuntu.com](https://www.ubuntu.com/search?q=intel+realsense), it can’t be found by [searching developer.ubuntu.com](https://developer.ubuntu.com/en/search/?q=intel+realsense) (zero results!), and it can’t be found even by searching tutorials.ubuntu.com (since as a new separate site it doesn’t have its own search function, work that will need doing once there is more than one page of tutorials).
- Though there are only six tutorials so far, [one of them](https://tutorials.ubuntu.com/tutorial/setup-ubuntu-core-intel-joule) is (as I mentioned) identical in scope to [a developer.ubuntu.com article](https://developer.ubuntu.com/core/get-started/intel-joule). Similarly, [another tutorial](https://tutorials.ubuntu.com/tutorial/create-your-own-core-image) is identical in scope to [a docs.ubuntu.com article](https://docs.ubuntu.com/core/en/guides/build-device/image-building). This is not a bad thing — some people learn better with one format, other people with another — but nowhere is this choice actually offered. People will only ever arrive at one or the other by accident.
- If, having completed the Intel Joule tutorial, you want to try the same thing with a Raspberry Pi, you’re at a dead end, even though [we have an article on doing that](https://developer.ubuntu.com/core/get-started/raspberry-pi-2-3). If you were on developer.ubuntu.com you’d see it linked from the same place as the Joule materials, but because you’re on tutorials.ubuntu.com you don’t. There will always be dozens of topics that are covered only in one format, so arranging information by format rather than by topic will always produce needless dead ends.

As more tutorials are published, navigation problems like these will proliferate. And since you mention [docs.ubuntu.com](https://docs.ubuntu.com/), that site suffers similarly: its separation leads to many links being marked as external, so inevitably one (“Read the MAAS documentation”) is marked as external by accident; none of the internal pages link to the relevant product site, flummoxing you if you arrive from a search engine; the custom navigation is so unusual that none of its pages even link back to the docs.ubuntu.com main page; and [developer.ubuntu.com’s newly-rebuilt Core section](https://developer.ubuntu.com/core) consists entirely of things that could reasonably be described as “documentation”, but then has [a “Documentation” page](https://developer.ubuntu.com/core/documentation) that does nothing except link to separate “documentation”, because that other documentation happens to be hosted on a different site, because it happens to be generated by a different CMS, which fact is of no relevance to users whatsoever.

All of these could be reported as separate issues. As you say, integrating with developer.ubuntu.com would not magically make everything easy to find. And I’m sure having different CMSes serving the non-navigation parts of different pages on a single site is non-trivial. But if they did, so the tutorials were integrated into the existing site, few if any of these issues would have occurred in the first place. Trying to address them on separate sites will be pushing water uphill.
